export const GETINBOXMAILS = "GETINBOXMAILS";
export const GETSPAMMAILS = "GETSPAMMAILS";
export const GETDELETEDMAILS = "GETDELETEDMAILS";
export const SELECTEDMAIL = "SELECTEDMAIL";
export const DELETEMAIL = "DELETEMAIL";
export const FLAGMAIL = "FLAGMAIL";
